# Generated by Django 5.0.1 on 2024-01-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
    ]
