# Generated by Django 5.0.1 on 2024-01-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_owner_comment'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='user_wishlist', to='book.book'),
        ),
    ]
