# Generated by Django 5.0.1 on 2024-01-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_lat_user_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
