# Generated by Django 5.0.1 on 2024-01-30 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
