# Generated by Django 5.0.1 on 2024-01-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
