# Generated by Django 5.0.1 on 2024-01-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_photo_url_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='house_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
