# Generated by Django 4.2.2 on 2024-01-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.JSONField(blank=True, default=list)),
                ('genres', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
