# Generated by Django 5.0.1 on 2024-01-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
