# Generated by Django 5.0.1 on 2024-01-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_requirements_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='requirements_loan',
            field=models.TextField(blank=True, default=''),
        ),
    ]
