# Generated by Django 5.0.1 on 2024-01-05 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_owner_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(10, message='Certifique-se de que a nota seja de no máximo 10')]),
        ),
    ]
