# Generated by Django 5.0.1 on 2024-01-18 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(10, message='Certifique-se de que a nota seja de no máximo 10')]),
        ),
    ]
