# Generated by Django 5.0.1 on 2024-01-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_requirements_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
