# Generated by Django 5.0.1 on 2024-01-21 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='creator',
            new_name='owner',
        ),
    ]
