# Generated by Django 5.0.1 on 2024-01-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rename_creator_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_in_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
