# Generated by Django 5.0.1 on 2024-03-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='from_field',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='visualized',
            field=models.BooleanField(default=False),
        ),
    ]
